<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
       <TargetFramework>net8.0</TargetFramework>
        <AssemblyName>intapscamis.camis.domain</AssemblyName>
        <RootNamespace>intapscamis.camis.domain</RootNamespace>
        <!-- Modern .NET features -->
        <ImplicitUsings>enable</ImplicitUsings>
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
    </PropertyGroup>

    <ItemGroup>
		<PackageReference Include="DocumentFormat.OpenXml" Version="3.0.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.4" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="8.0.0" />
        <PackageReference Include="Stateless" Version="5.17.0" />
        <PackageReference Include="System.Text.Json" Version="8.0.5" />
		<PackageReference Include="RestSharp" Version="111.0.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\camis.data\camis.data.csproj" />
        <ProjectReference Include="..\camis.types\camis.types.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Extensions\" />
      <Folder Include="Infrastructure\Database\" />
    </ItemGroup>
    
</Project>
